name: PRODUCTION - Deploy API
'on':
  push:
    branches:
      - api
    paths:
      - 'apps/api/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
    # env:
    # SLACK_WEBHOOK_URL: '${{ secrets.SLACK_NOTIFICATION_WEBHOOK }}'
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: install_node
        name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - id: setup_pnpm
        name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - id: install_packages
        name: Install packages
        run: pnpm install --filter api

      - name: Copy firebase.json file
        run: cp firebase.json apps/api/firebase.json

      - id: build
        name: Build
        env:
          NODE_ENV: production
        run: pnpm build --filter api

      - id: authentication
        name: Authentication
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SWORLD_PROD }}'

      - id: deploy
        name: Deploy
        run: pnpm --filter=api deploy:dev
